### ISSUE TITLE
Working with paths

### ISSUE THREAD

**Issue by vchuravy** [dcjones/Compose.jl#116]
So I decided to use `Compose` to computationally create tags. I managed to create a figure that looks correct in `IPython` by using `paths` which seems to be a under documented but very useful feature. But when I try to export this to `PNG` or `PDF` the parts of the figure that are defined via paths disappear and when I use `SVG` the picture looks right but there is a small rendering bug.

The code is a bit involved so I put it in a gist https://gist.github.com/vchuravy/86f1383def946288c7b2

**Comment by shashi** [comment]
I have encountered the rendering bug too. If you take a path from an SVG made in Inkscape and parse it into the compose Path form, it's not going to look the same when I render it back to SVG. The way I got around this is by adding more nodes to the path in Inkscape and trying it out with Compose until I got a satisfactory picture.

As for `PNG` and `PDF` backends, they do not have methods to render paths yet.

**Comment by dcjones** [comment]
@shashi is right, I haven't implemented paths on the cairo backends yet. Can you point out the rendering bug? This is what I get on `SVG`.

![screen shot 2015-04-17 at 10 31 00 am](https://cloud.githubusercontent.com/assets/210361/7207264/ed81ed54-e4ec-11e4-9ec0-e1abf120b2a3.png)

**Comment by dcjones** [comment]
I'm adding support for paths in the cairo backend now. I made some abstract art for us to enjoy in the meantime.

![try](https://cloud.githubusercontent.com/assets/210361/7207996/57282e8a-e4f2-11e4-9571-ee38c9cf24d3.png)

**Comment by dcjones** [comment]
Paths should render correctly on PNG, PDF, PS. I found a couple bugs on SVG that I fixed in that commit as well. If you continue to see rendering bugs, please reopen.

**Comment by vchuravy** [comment]
Sorry for my late reply.
The rendering bug I saw was when opening the file with gimp. Inkscape
managed to handle it properly.

Thank you for the path implementation in the cairo backend. Compose is
quickly shaping up to be one of my favourite tool for creating graphics
besides tikz/pgf
