### ISSUE TITLE
Correct way to get size of a text node?

### ISSUE THREAD

**Issue by IainNZ** [dcjones/Compose.jl#117]
e.g. I've got a whole lot of snippets of text I want to place, and I want to know their widths before I place them. Whats the "correct" way to do this?

**Comment by IainNZ** [comment]
Oh, `text_extents`?

**Comment by dcjones** [comment]
Right, `text_extents(fontname, fontsize, strings...)` returns an array with a width/height tuple for each string.

**Comment by IainNZ** [comment]
Is there any way to get the "default" fontname and fontsize? How are those selected?

**Comment by dcjones** [comment]
There are `Compose.default_font_family` and `Compose.default_font_size`, but now that I'm looking, I don't think `default_font_family` is actually being used. :confused:

**Comment by IainNZ** [comment]
So,

```julia
ext = text_extents("Helvetica",10px,"Compose.jl")
width = ext[1][1].abs
height = ext[1][2].abs
@show width
@show height
ratio = height/width
set_default_graphic_size(4inch,(4*ratio)inch)
compose(context(units=UnitBox(0,0,width,height)),
text(0,1,"Compose.jl"),
rectangle(0,0,width,height),
fontsize(10px),font("Helvetica"),
fill("red"),stroke("black"))
```

I'd have expected the text to be the size of the rectangle and the overall image, but its not even close. The 10px is arbitrary because I don't know really what to put - I guess inches because the plots in inches...

**Comment by IainNZ** [comment]
So this correct actually:

```
fsize = 0.8inch
ext = text_extents("Helvetica",fsize,"Compose.jl")
width = ext[1][1].abs
height = ext[1][2].abs
@show width
@show height
ratio = height/width
set_default_graphic_size(4inch,(4*ratio)inch)
compose(context(units=UnitBox(0,0,width,height)),
text(0,14.8,"Compose.jl"),
rectangle(0,0,width,height),
fontsize(fsize),font("Helvetica"),
fill("red"),stroke("black"))
```

although the manual positioning of the text sucks, but can be fudged.

**Comment by dcjones** [comment]
The `text` form has optional alignment arguments, so you can write this as
```julia
text(0.5w, 0.5h, "Compose.jl", hcenter, vcenter)
```

**Comment by dcjones** [comment]
So if I were going to draw a bunch of text labels with rectangles around them I'd do something like
```julia
function textrect(xcenter, ycenter, label, fontfamily, fontsize)
    width, height = text_extents(fontfamily, fontsize, label)[1]
    compose(context(xcenter - width/2, ycenter - height/2, width, height),
            (context(), rectangle(), fill(nothing), stroke("red")),
            text(0.5w, 0.5h, label, hcenter, vcenter))
end

compose(context(), 
        font("sans"), fontsize(11pt),
        [textrect(rand()*cx, rand()*cy, randstring(5), "sans", 11pt) for _ in 1:500]...)
```
![try](https://cloud.githubusercontent.com/assets/210361/7246076/2054cb5e-e7ac-11e4-8d90-ac82c5d0b796.png)

I hope that helps. Sorry this is confusing.

**Comment by IainNZ** [comment]
That was really helpful, and I'm making good progress. Looking forward to releasing the final product!
