### ISSUE TITLE
Consistency in "origins"

### ISSUE THREAD

**Issue by IainNZ** [dcjones/Compose.jl#118]
* Circles are defined by their center
* Rectangles (and contexts, I suppose) are defined by their top left corner
* Text labels are defined by their bottom left corner (I think?)

**Comment by IainNZ** [comment]
The text-rectangle mismatch makes putting a text on a rectangle a bit confusing - unless there is some smarter way to do things?

**Comment by aviks** [comment]
Text is usually laid out based on its baseline. That's how fonts are measured, for eg.  Left-right text laid out from the left, while right to left text should be laid out from the right. Not sure the kind of consistency you ask for is a good idea.

**Comment by IainNZ** [comment]
Yeah probably not worth it
