### ISSUE TITLE
hcat/vcat, simple table?

### ISSUE THREAD

**Issue by lobingera** [dcjones/Compose.jl#121]
compose( is tree oriented (as defined).
How would something like a stacking of items, so putting drawings into contexts and then concatenating them into a box look like?

**Comment by dcjones** [comment]
There's `hstack`, `vstack`, and `gridstack` which I think do what you want.

```julia
c1 = compose(context(0, 0, 1inch, 1inch), circle(), fill("tomato"))
c2 = compose(c1, fill("steelblue"))
c3 = compose(c1, fill("powderblue"))
c4 = compose(c1, fill("oldlace"))

hstack(c1, c2)
```
![fuck-shit-hstack](https://cloud.githubusercontent.com/assets/210361/8272440/7a5efb30-17f7-11e5-93b4-0ca2eccd4e87.png)


```julia
vstack(c1, c2)
```
![fuck-shit-vstack](https://cloud.githubusercontent.com/assets/210361/8272441/800d5cd4-17f7-11e5-9cb1-0c7c52f2d06e.png)


```julia
gridstack([c1 c2; c3 c4])
```
![fuck-shit-gridstack](https://cloud.githubusercontent.com/assets/210361/8272443/865ad9cc-17f7-11e5-970e-1d770fcc95d1.png)

**Comment by lobingera** [comment]
... maybe rather a documentation issue ...
