### ISSUE TITLE
Compressed coordinates when drawing a dotted circle

### ISSUE THREAD

**Issue by vchuravy** [dcjones/Compose.jl#136]
So I am running into a weird problems where it seems that my y-coordinate gets compressed.

````julia
using Compose

r = 0.3
cx = .5
cy = .5

n = 20

contexts = Context[]

circ = compose(context(), circle(cx, cy, r), fill("white"), stroke("black"))

θ = 0.0
step = 2π/n
for i in 1:20
    px = cx + r*cos(θ)
    py = cy + r*sin(θ)
    c = compose(context(), circle(px, py, 0.01), fill("tomato"))
    push!(contexts, c)
    θ += step
end

compose(context(), contexts..., circ)
````

This is on Julia v0.4
````julia
julia> versioninfo()
Julia Version 0.4.0-dev+6846
Commit 9fce682 (2015-08-20 02:25 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libblas
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-3.6.2
````

and the current Compose master
````julia
julia> Pkg.status("Compose")
 - Compose                       0.3.13+            master
````

**Comment by vchuravy** [comment]
I just now noticed that this only occurs when plotting in IJulia drawing to SVG works fine. 
Setting a default_graphic_size solves that problem, but it still baffles me that the circle is drawn correctly, but dots that should appear on that circle are not.

````julia
Compose.set_default_graphic_size(5cm, 5cm)
````

This also appears if one uses the SVG path languages and they have the same problem of appearing compressed in the y-axis, while a circle drawn on top is not.

**Comment by dcjones** [comment]
What's happening is a little subtle. Bare numbers are treated as "context units" which go from 0 to 1 within the bounds of the parent context. There are separate units for x and y called `cx`, `cy`.

The issue is that when a radius for a circle is a bare number, it's (somewhat arbitrarily) treated as `cx` coordinates. When you compute the offset for `py` as `r*sin(θ)` it's assumed to be `cy` coordinates, but since the radius was `cx` coordinates, and the context is not a square, it gets stretched. A simple fix is to just make the coordinates explicit for `py`.

```julia
py = cy*Compose.cy + r*sin(θ)*Compose.cx
```

**Comment by vchuravy** [comment]
@dcjones thanks that works nicely. 

Would you be interested in having code that creates segment of circles in Compose?

````julia
"""
Calculates a point on the circle given by (cx, cy, r),
according to the angle θ in radians
"""
function point_on_circle(cx, cy, r, θ)
    x = cx + r * cos(θ)
    y = cy + r * sin(θ)
    (x, y)
end

"""
Create a segment of a circle
cx, cy : centre
r: radius
endθ: angle of end point in radians
startθ: angle of starting point in radians
"""
function segment(cx, cy, r, endθ, startθ = 0.0)
    cx = cx * Compose.cx
    cy = cy * Compose.cy
    r = r * Compose.cx

    startP = point_on_circle(cx, cy, r, startθ)
    endP = point_on_circle(cx, cy, r, endθ)

    sweep = startθ < endθ ? 1 : 0

    compose(context(),
            path([
                :M, startP..., # Move (not draw) to start
                :A, r, r, 0, 0, sweep, endP..., # Arc from start to end
                :L, cx, cy, # Line to center
                :L, startP...])) # line to starting point

end
````
