### ISSUE TITLE
Compose doesn't load with Julia 3

### ISSUE THREAD

**Issue by troelsfrostholm** [dcjones/Compose.jl#160]
With a clean install of the latest stable Julia version (0.3.11) and Compose v"0.3.16" installed using Pkg,  I get the following:

    julia> using Compose
    ERROR: LOAD_CACHE_PATH not defined
     in include at /opt/homebrew-cask/Caskroom/julia/0.3.11/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
     in include_from_node1 at /opt/homebrew-cask/Caskroom/julia/0.3.11/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
     in reload_path at loading.jl:152
     in _require at loading.jl:67
     in require at loading.jl:51
    while loading /Users/troels/.julia/v0.3/Compose/src/Compose.jl, in expression starting on line 148

The problem appears to be that LOAD_CACHE_PATH is a new Julia 4 feature. As a workaround, I have removed the offending statement (which is only used in an error message), in which case Compose loads and works as expected.

**Comment by dcjones** [comment]
Sorry about that, it should be fixed after updating.
