### ISSUE TITLE
Tagging a new release? (Input from contributors)

### ISSUE THREAD

**Issue by timholy** [dcjones/Compose.jl#171]
For other folks intimately involved with this package (@shashi, @darwindarak, etc), what do people think about tagging a new release? Currently the experience for Immerse users is awful because of long screenfulls of deprecation warnings; this is fixed by #167 and https://github.com/JuliaGraphics/Immerse.jl/pull/47. Locally (probably because I'm using https://github.com/JuliaGraphics/Immerse.jl/pull/47) I'm also getting Pkg errors:
```jl
julia> Pkg.free("Reactive")
INFO: Freeing Reactive
WARNING: Compose is fixed at 0.3.18+ conflicting with requirement for Immerse: [0.3.19,∞)
INFO: Upgrading Escher: v0.1.0 => v0.2.1
INFO: Upgrading Mux: v0.1.1 => v0.2.0
INFO: Installing Plots v0.4.2
INFO: Removing Color v0.2.11
INFO: Rolling back install of Plots
INFO: Rolling back Mux from v0.2.0 to v0.1.1
INFO: Rolling back Escher from v0.2.1 to v0.1.0
ERROR: SystemError: mkdir: File exists
 in mkdir at file.jl:42
 in cptree at file.jl:100
 in cp at file.jl:120
 in rename at fs.jl:121
 in remove at pkg/write.jl:50
 in resolve at ./pkg/entry.jl:459
 in resolve at pkg/entry.jl:404
 in anonymous at pkg/entry.jl:198
 in transact at pkg/git.jl:97
 in _checkout at pkg/entry.jl:190
 in free at pkg/entry.jl:220
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in free at pkg.jl:40
```
I'm going to try to fix this separately, but in the meantime it would be great to tag a new release of Compose and Gadfly. Do folks think we can deal with any problems that crop up in the absence of @dcjones? (Hopefully he's having a lovely time sunbathing in Fiji or scaling Mt. Everest or something similarly exciting, and not suffering from RSI and needing to take a break from typing. Or perhaps he's just swamped by other duties, an all-too familiar state for me.)

My main concern is that the Measures.jl transition is a pretty big one.

**Comment by timholy** [comment]
CC also @Godesimo.

**Comment by timholy** [comment]
Oops, misspelled that (sorry): @Godisemo.

**Comment by shashi** [comment]
I'd say tag it, I'll help with issues if they crop up.

**Comment by tbreloff** [comment]
I expect the Gadfly/Immerse backends in Plots might break once it's tagged,
but (although I may not want it) it's best to rip the band-aid off and see
what the cut looks like...

**Comment by aviks** [comment]
@tbreloff do you want to tag a new version of Plots with a max-version of Gadfly/Compose, so that your users can continue using it while you fix the breakage?

**Comment by timholy** [comment]
If you want to test the Immerse backend, just update to master on Compose and `teh/measures` on Immerse. I just ran it, and all the Gadfly tests looked fine by eye (PyPlot had some issues on my system, though).

**Comment by tbreloff** [comment]
That's a good idea.  I've been wanting to tag a new version anyways.  (Tim:
if you're seeing any issues on the latest Plots master, can you open an
issue with the commands you used?)

**Comment by timholy** [comment]
For the error at the top, see https://github.com/JuliaLang/julia/pull/14015.

**Comment by tbreloff** [comment]
Fixing the Colors parsing unveiled the underlying cause of the error (passing a Colorant into the constructor of Gadfly's HLineGeometry/VLineGeometry).  After fixing (and with the Colors PR) the Plots tests are passing for Gadfly.

(Immerse is untested... I can't even clone it without breaking `Pkg` completely.  I'll wait to test until this tagging smoke clears.)

**Comment by timholy** [comment]
Fixed by https://github.com/JuliaLang/METADATA.jl/pull/4051. @tbreloff, hopefully the Pkg mess is cleared now?
