### ISSUE TITLE
Inconsistent behavior of circle(xs,ys,rs)

### ISSUE THREAD

**Issue by Sacha0** [dcjones/Compose.jl#172]
`circle(xs, ys, rs)` in 55eabfe21ed94c1a8b88babd4abfb444fb695ef6/src/form.jl#L267-L275 passes radius `r in rs` through `size_measure(r)` in calling the underlying CirclePrimitive constructor, by default interpreting the radius in millimeters, whereas all related methods ultimately pass `r` through `x_measure(r)`, by default interpreting the radius in context units; compare the output of `circle(0.5, 0.5, 0.1)` and `circle([0.5], [0.5], [0.1])`.

Formerly `circle(xs, ys, rs)`'s behavior was consistent with that of the related methods and documentation; this changed in ad3e0387e13cd2fd70ebc78b35cf6ca48c33166f and went mainstream with this morning's release.  Is the inconsistent behavior intended?  If not, what is the intended behavior?

If it would be helpful, given clarification of the intended behavior I would be happy to submit a PR.  Thanks!

**Comment by timholy** [comment]
I can't speak for @dcjones intentions, but I suspect that the goal is to allow one to supply the circle's parameters in a wider range of units. But certainly there needs to be internal consistency. A PR fixing this would be great; we'll do our best to evaluate it in @dcjones's absence, and tag a new release.

**Comment by Sacha0** [comment]
#176
