### ISSUE TITLE
Rotation ignored?

### ISSUE THREAD

**Issue by Sacha0** [dcjones/Compose.jl#174]
```julia
canvas = compose(context(rotation=Rotation(pi/4)), ellipse(0.5, 0.5, 0.5, 0.25));
image = PDF("rotationtest.pdf", 100px, 100px);
draw(image, canvas)
```
behaves as expected on Compose.jl 0.3.18 / Julia 0.4.1, producing a rotated ellipse. In contrast Compose.jl 0.4.0 / Julia 0.4.1 draws an unrotated ellipse and likewise with Compose.jl master / Julia 0.4.1. The same holds for the SVG backend.

Did relevant expected behavior change between 0.3.18 and 0.4.1? If not, I will try to better isolate this issue after constructing a PR for #172. Thanks, and best!

**Comment by simleb** [comment]
I second that. I can't even rotate a line or a polygon. I tried to reinstall Cairo and Compose to no avail.

**Comment by Sacha0** [comment]
Additional information: 48dc3cf3b84c3747b50f044737d8360634d37a06 is the most recent commit that I can confirm exhibits this issue. 2b99f69c6d43acc8b6b81b50ec014a0cf04cf0d5 is the most recent commit that I can confirm does not exhibit this issue. The commits between 2b99f69c6d43acc8b6b81b50ec014a0cf04cf0d5 and 48dc3cf3b84c3747b50f044737d8360634d37a06 are not adequately functional on my 0.4.1 installation to complete the test in the first comment.
