### ISSUE TITLE
ERROR: LoadError: LoadError: Not an `in` expression 

### ISSUE THREAD

**Issue by kleinash** [dcjones/Compose.jl#204]
Error when trying to use Gadfly or Compose: 
Version 0.5.0-dev+3438 (2016-04-07 15:46 UTC), Ubuntu 14.04

###
julia> using Compose
INFO: Precompiling module Compose...
ERROR: LoadError: LoadError: Not an `in` expression
 in include(::ASCIIString) at ./boot.jl:234
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 in include(::ASCIIString) at ./boot.jl:234
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 [inlined code] from ./boot.jl:237
 in anonymous at ./<no file>:4294967295
 in eval(::Module, ::Any) at ./boot.jl:237
 [inlined code] from ./sysimg.jl:11
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/ashley/.julia/v0.5/Compose/src/form.jl, in expression starting on line 188
while loading /home/ashley/.julia/v0.5/Compose/src/Compose.jl, in expression starting on line 80
ERROR: Failed to precompile Compose to /home/ashley/.julia/lib/v0.5/Compose.ji
 in error(::ASCIIString) at ./error.jl:21
 in compilecache(::ASCIIString) at ./loading.jl:496
 in compilecache(::Symbol) at ./loading.jl:485
 in require(::Symbol) at ./loading.jl:355
 in eval(::Module, ::Any) at ./boot.jl:237
###

Am I doing something wrong?

**Comment by lobingera** [comment]
Compose.jl is not up to date with recent v0.5.

**Comment by lobingera** [comment]
btw: could you please post a Pkg.status() along this?

**Comment by timholy** [comment]
Seems to work if you check out master of Compose, probably thanks to #194.

**Comment by kleinash** [comment]
I reverted to 0.4 unfortunately - too many other packages were breaking.
