### ISSUE TITLE
composejl.org domain name has expired

### ISSUE THREAD

**Issue by Hydrotoast** [dcjones/Compose.jl#210]
Looks like the domain name for the documentation has expired. Are there plans to renew this or create documentation elsewhere?

**Comment by rsrock** [comment]
Probably easiest to migrate the docs to gh-pages

**Comment by Hydrotoast** [comment]
I tried to generate a `gh-pages` branch on a fork but it seems like the current documentation engine `Judo` is deprecated in favor of `Documenter`: https://github.com/dcjones/Judo.jl/issues/24.

**Comment by rsrock** [comment]
Ah, yes, dcjones made Judo before the current docsystem.  We might want to consider migrating the current docs to Documenter.  That's not a small project, but it can be done. I did it over at Images.jl a while ago.

**Comment by Hydrotoast** [comment]
Handled by #214
