### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by tlnagy** [dcjones/Compose.jl#213]
Now that https://github.com/dcjones/Compose.jl/pull/211 is merged, @shashi could you tag a new release of `Compose` and then we'll be close to getting Gadfly up and running on v0.5. Thanks!

ref: https://github.com/dcjones/Gadfly.jl/issues/866

**Comment by shashi** [comment]
PR opened https://github.com/JuliaLang/METADATA.jl/pull/5955

**Comment by tlnagy** [comment]
Thanks! 🎉
