### ISSUE TITLE
Where did the boundingbox function go?

### ISSUE THREAD

**Issue by Keno** [dcjones/Compose.jl#82]
There used to be a `boundingbox` function which was very useful, but I can't seem to find it any more.

**Comment by IainNZ** [comment]
This was closed by https://github.com/dcjones/Compose.jl/pull/83 right?

**Comment by Keno** [comment]
Yes

**Comment by IainNZ** [comment]
Thanks! I needed to compute some bounding boxes and got worried when I saw this
