### ISSUE TITLE
Turn off fontspec for PGF backend

### ISSUE THREAD

**Issue by msimberg** [dcjones/Compose.jl#87]
It would be great if it were possible to force the PGF backend to ignore any fonts in the theme so that the plot would just use whatever fonts are used in the latex document.

It seems like this would just be a matter of forcing `img.fontfamily` in the PGF constructor to be `nothing` if a flag is set, but I couldn't quite figure out where it gets set to something else. I could have a try at implementing this myself with some help.

@darwindarak?

**Comment by bastinat0r** [comment]
@msimberg Same here. I want to use a plot created with Gadfly in my paper and the thing that does not work at the moment is removing fontspec. (Of coure a solution would be to just remove all lines with \fontspec)
Anyway I would be glad to know how you solved this

**Comment by msimberg** [comment]
@bastinat0r Unfortunately I don't have a fix for this except for simply removing the lines with fontspec (at least they're easy to remove). I ended up just removing them with my Makefile when building my thesis, which was a fairly pain-free way to do it.

**Comment by bastinat0r** [comment]
Been there done that ;)
For anyone else searching: ``` sed -i '/^\\fontspec/d' $file ```

**Comment by darwindarak** [comment]
`fontspec` is only used to make the outputs consistent across the different backends.  Maybe we can add a keyword argument like `usedefaultfonts` in `draw`.

**Comment by bastinat0r** [comment]
Thats exactly what I had looked for. I thought of calling something like ```draw(PGF(filename, 10cm, 10cm, enablefontspec=false), plot)``` – I don't really know what would be a good name for this parameter.

**Comment by darwindarak** [comment]
I've submitted PR #159 to do this.  Can you guys check to see if this is what you are looking for?

**Comment by dcjones** [comment]
Fixed by Darwin in #159.
